package de.ari24.packetlogger.packets;

import com.google.gson.JsonObject;
import de.ari24.packetlogger.mixin.LoginHelloS2CPacketAccessor;
import de.ari24.packetlogger.utils.ConvertUtils;
import net.minecraft.network.encryption.NetworkEncryptionException;
import net.minecraft.network.packet.s2c.login.LoginHelloS2CPacket;

public class LoginHelloS2CPacketHandler implements BasePacketHandler<LoginHelloS2CPacket> {
    @Override
    public String name() {
        return "EncryptionRequest";
    }

    @Override
    public String url() {
        return "htthttps://wiki.vg/index.php?title=Protocol&oldid=18067#Encryption_Request";
    }

    @Override
    public JsonObject description() {
        JsonObject jsonObject = new JsonObject();
        jsonObject.addProperty("general", "After the server sends this packet, the client will try to authenticate with the mojang session servers.");
        jsonObject.addProperty("wikiVgNotes", "See https://wiki.vg/Protocol_Encryption for more information");
        jsonObject.addProperty("serverId", "Appears to be empty (TODO), max. 20 characters long");
        jsonObject.addProperty("publicKey", "The server's public key, in bytes.");
        jsonObject.addProperty("rawPublicKey", "If the public key could not be decoded, this will contain the raw public key (encoded)");
        jsonObject.addProperty("verifyToken", "A sequence of random bytes generated by the server, used to verify the client's identity.");
        return jsonObject;
    }

    @Override
    public JsonObject serialize(LoginHelloS2CPacket packet) {
        JsonObject jsonObject = new JsonObject();
        jsonObject.addProperty("serverId", packet.getServerId());

        try {
            jsonObject.add("publicKey", ConvertUtils.GSON_INSTANCE.toJsonTree(packet.getPublicKey().getEncoded()));
        } catch (NetworkEncryptionException exception) {
            jsonObject.addProperty("publicKey", "Could not decode encoded rsa public key");

            LoginHelloS2CPacketAccessor accessor = (LoginHelloS2CPacketAccessor) packet;
            jsonObject.add("rawPublicKey", ConvertUtils.GSON_INSTANCE.toJsonTree(accessor.getPublicKey()));
        }

        jsonObject.add("verifyToken", ConvertUtils.GSON_INSTANCE.toJsonTree(packet.getNonce()));
        return jsonObject;
    }
}
